databases:
  - name: doctor-api
    databaseName: doctor_api_jou8
    user: doctor_api_jou8_user

services:
  - type: web
    name: book-doctor-api
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: doctor_api_jou8
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false